name: CI
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.11.0
      - run: sbt +headerCheckAll +scalafmtCheckAll scalafmtSbtCheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - 1.8.0
          - 1.11.0
        scala:
          - 2.12.13
          - 2.13.5

  avro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.11.0
      - run: sbt -Davro.version=1.8.2 test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.11.0
      - run: |
          sbt coverage test coverageAggregate
          bash <(curl -s https://codecov.io/bash)
